### ISSUE TITLE
Wrong price info for COCK

### ISSUE THREAD

**Issue by cq89** [chartexpro/feature-requests-bugs#12]
Can you guys change the price info back to the correct COCK token.

https://www.dextools.io/app/uniswap/pair-explorer/0x59926f623909e06b8e8590b0b9b5500cbd2b7f84

Thanks, it was showing this before and has recently changed to a different one.

**Comment by chartexpro** [comment]
Forced market refresh, picked up new pair based on volume criteria. Closing issue

**Comment by cq89** [comment]
Theres no other ticker by COCK that has more than 600K volume like the link to the one stated above.
