### ISSUE TITLE
Wrong BACON shown

### ISSUE THREAD

**Issue by voyager** [chartexpro/feature-requests-bugs#2]
Submitting a bug for the user Forever Bull:

Hi! Can you fix BACON please, on chartex.pro the chart of the Scam project is displayed. Here is the real one — https://uniswap.info/token/0x175ab41e2cedf3919b2e4426c19851223cf51046.

The volume of the coin that I specified = 500.000$+.

Other BACONs have no volume at all.

**Comment by chartexpro** [comment]
An issue with liquidity filtering has now been resolved, which should allow you to get your fix of BACON. Mmm BACON
