### ISSUE TITLE
Please add capabilities to show ESD/USDC pair chart in ChartEx 

### ISSUE THREAD

**Issue by xgast** [chartexpro/feature-requests-bugs#25]
I can't see chart of ESD in ChartEx, It's trade with USDC pair only in Liquidity pool, any solution to make it work with ChartEx, currently It has $400k trade volume & more than $2M liquidity in uniswap, thanks 🙏🏻

**Comment by chartexpro** [comment]
USDC pairs are not currently supported but this will be addressed in a future release
