### ISSUE TITLE
[Request/Suggestion] Charting Liquidity over time

### ISSUE THREAD

**Issue by thejeetsons** [chartexpro/feature-requests-bugs#72]
Chartex currently shows the liquidity for a trading pair in real time. I'd like to be able to see what the liquidity was in the past to use as an additional tool to gauge interest in a particular protocol. If people are buying and not LP farming it is quite a bit different to me in terms of what kind of trade I'm looking to do compared to more people buying and LP farming.

This data would further enhance the value that holding CHART gives its users.

**Comment by chartexpro** [comment]
ChartEx Metamorphosis has Liquidity and Liquidity Delta events as indicators
