### ISSUE TITLE
after closing browser incorrect charts re-open

### ISSUE THREAD

**Issue by 0xWeth** [chartexpro/feature-requests-bugs#85]
I have 3 metamorphosis chartex tabs opened in my browser -( thats how i work),
each saved to their own name, alt 1, alt 2, alt 3 etc

If i close the browser and reopen, (I have auto-open previous tabs on within my browser) 
the three tabs tab will all load as Alt1 but the actual crypto is still correct for that tab, alt 2 and alt 3 still load BUT they are all called alt 1 and they dont display the correct lines and patterns that Ive drawn, 
so I have to manually load the correct crypto in each tab - Its time consuming and annoying.

Im using brave browser on a mac
 Trading view works ok, I can reopen the browser and the correctly saved crypto opens in each tab, so Im sure you can work this out with chartex

**Comment by 0xWeth** [comment]
Anyone reading this?

Im still having this problem - Its been buggy like this for months

It really slows down the workflow - and if you accidentally click save with the wrong crypto autoloaded, you could lose your very important charts

**Comment by chartexpro** [comment]
This is not a bug, ChartEx is not designed for multi-tab operation. It will be added as a low priority task to investigate
